// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cheer.sql

package db

import (
	"context"
)

const randomCheerByZone = `-- name: RandomCheerByZone :one
SELECT text FROM cheer_templates
WHERE zone = $1
ORDER BY random()
LIMIT 1
`

func (q *Queries) RandomCheerByZone(ctx context.Context, zone string) (string, error) {
	row := q.db.QueryRow(ctx, randomCheerByZone, zone)
	var text string
	err := row.Scan(&text)
	return text, err
}
