// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertStepEvents implements pgx.CopyFromSource.
type iteratorForInsertStepEvents struct {
	rows                 []InsertStepEventsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertStepEvents) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertStepEvents) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].SteppedAt,
		r.rows[0].Magnitude,
	}, nil
}

func (r iteratorForInsertStepEvents) Err() error {
	return nil
}

func (q *Queries) InsertStepEvents(ctx context.Context, arg []InsertStepEventsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"step_events"}, []string{"user_id", "stepped_at", "magnitude"}, &iteratorForInsertStepEvents{rows: arg})
}
