// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type StepEvent struct {
	ID        int64
	UserID    string
	SteppedAt pgtype.Timestamptz
	Magnitude float32
	CreatedAt pgtype.Timestamptz
}
