// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: steps.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSteps = `-- name: CountSteps :one
SELECT count(*) FROM step_events
WHERE user_id = $1 AND stepped_at BETWEEN $2 AND $3
`

type CountStepsParams struct {
	UserID      string
	SteppedAt   pgtype.Timestamptz
	SteppedAt_2 pgtype.Timestamptz
}

func (q *Queries) CountSteps(ctx context.Context, arg CountStepsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSteps, arg.UserID, arg.SteppedAt, arg.SteppedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteStepEvents = `-- name: DeleteStepEvents :execrows
DELETE FROM step_events WHERE user_id = $1
`

func (q *Queries) DeleteStepEvents(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStepEvents, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

type InsertStepEventsParams struct {
	UserID    string
	SteppedAt pgtype.Timestamptz
	Magnitude float32
}

const stepsPerMinute = `-- name: StepsPerMinute :many
SELECT date_trunc('minute', stepped_at)::timestamptz AS minute, count(*) AS steps
FROM step_events
WHERE user_id = $1 AND stepped_at BETWEEN $2 AND $3
GROUP BY 1
ORDER BY 1
`

type StepsPerMinuteParams struct {
	UserID      string
	SteppedAt   pgtype.Timestamptz
	SteppedAt_2 pgtype.Timestamptz
}

type StepsPerMinuteRow struct {
	Minute pgtype.Timestamptz
	Steps  int64
}

func (q *Queries) StepsPerMinute(ctx context.Context, arg StepsPerMinuteParams) ([]StepsPerMinuteRow, error) {
	rows, err := q.db.Query(ctx, stepsPerMinute, arg.UserID, arg.SteppedAt, arg.SteppedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StepsPerMinuteRow
	for rows.Next() {
		var i StepsPerMinuteRow
		if err := rows.Scan(&i.Minute, &i.Steps); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
